FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y python3.12 python3.12-dev python3-pip python3-venv

WORKDIR /usr/src/summarize_bot
ENV PYTHONPATH="/usr/src/summarize_bot"
COPY requirements.txt .

RUN python3 -m venv .venv
RUN .venv/bin/python3 -m pip install -r requirements.txt
COPY . .

RUN apt-get update && apt-get -y install cron

COPY cronfile /etc/cron.d/cronfile
RUN chmod 0644 /etc/cron.d/cronfile
RUN crontab /etc/cron.d/cronfile
RUN touch /var/log/cron.log

CMD printenv > /etc/environment && cron && tail -f /var/log/cron.log